datalad/datalad-metalad

- datalad_metalad/__init__.py
- datalad_metalad/extractors/core.py
- datalad_metalad/extractors/tests/test_base.py
Now all IDs from the DataLad realm come with a 'datalad:' prefix, and a matching definition in the context.
This is safer (no accidental false-positives), and more compatible with using DataLad IDs in the context of 3rd-party metadata schemes.
> RF: Stop adding a default @base to the context, use explicit prefix

- datalad_metalad/__init__.py
- datalad_metalad/extractors/custom.py
- datalad_metalad/extractors/tests/test_custom.py
- datalad_metalad/tests/test_aggregate.py
- datalad_metalad/tests/test_extract.py
This will dramatically ease the homogenization of metadata across
sources, because uniform IDs can be used to match metadata documents
across sources.
> ENH: Let `custom` extractor inject dataset/file IDs if not present

- .travis.yml
DataLad requires 3.5 or higher.
> TST: remove Python 2.7 from testing environment

- datalad_metalad/aggregate.py
- datalad_metalad/tests/test_aggregate.py
This sits on top of #21 and attempts to fix #20.
I found two issues:
- (as Ben also noted) There was no condition which could do what is desired. I.e, whenever a subds had up-to-date metadata, but its meta data was unknown to the top, re-extraction in sub was enforced. I have added a switch to use pre-aggregated metadata (from the sub) even if sub's metadata was never aggregated to the top yet. After all this digging, it feels like a too-cheap solution to not have catastrophic consequences at one point, but for now the tests work (at least locally. Also Ben's new test)... But please check ;-)
- A change in #21 prevented an update of top's dataset info in the case of re-using sub's meta data that the top did not yet have, which let to the test failures Ben observed, I believe (see …
> disable re-extraction without sacrificing top-level updates

- Makefile
Same fix as in datalad. Handle whitespace in shell variable expansion properly
> BF: fix whitespace handling in Makefile

- datalad_metalad/extractors/tests/test_base.py
create's no_annex was deprecated in v0.13.0.
---
If this goes in as is, the required version for datalad would need to be bumped.
> TST: test_api_{annex,git}: Use annex instead of no_annex

- datalad_metalad/tests/test_aggregate.py
With datalad/datalad#4762, DataLad's tests have removed the use of
localhost as the target so that a Docker-based target [0] can more
easily be swapped in.  Use datalad-test here too.  It will work with
the current .travis.yml setup, where datalad-test points to localhost,
and will allow the Docker target to be used with the -metalad build at
datalad-extensions [1].
[0] https://hub.docker.com/r/dataladtester/docker-ssh-target
[1] https://github.com/datalad/datalad-extensions/pull/27#issuecomment-668217294
> TST: Prefer datalad-test over localhost as SSH target

- datalad_metalad/__init__.py
- datalad_metalad/add.py
- datalad_metalad/exceptions.py
- datalad_metalad/extract.py
- datalad_metalad/tests/test_add.py
- datalad_metalad/tests/test_base.py
- datalad_metalad/tests/test_extract.py
- requirements-devel.txt
This fixes #93, which in turn addresses the separation from metadata extraction and metadata storage in a metadata model instance.
This PR introduces a new metalad commando: meta-add. It is used to add metadata that was extracted by an extractor, or created by other means. The internal structure of the metadata is (will be) shared between: meta-extract, meta-add, and meta-dump.
This PR is a pre-condition to remove automated storage of metadata from meta-extract.
> Nf meta add

- datalad_metalad/dump.py
- datalad_metalad/extractors/core_dataset.py
- datalad_metalad/extractors/core_file.py
- datalad_metalad/tests/test_extract.py
This PR resolves issue #84 (and #82).
`meta-dump` will now output self-contained metadata-records that describe metadata associated with:
1. A dataset or dataset-element, i.e. file
2. An extractor name (although an extractor might not have been used to create the metadata, extractor_name still identifies the format/type of the metadata)
3. A set of parameters that were used during the "extraction" process.
Records are new-line separated JSON-strings
The resulting metadata records can be directly fed into `meta-add` (line by line for now, since `meta-add` does not support new-line separated input yet).
> NF Fix output of dump

- datalad_metalad/add.py
- datalad_metalad/extract.py
- datalad_metalad/extractors/core_dataset.py
- datalad_metalad/extractors/core_file.py
- datalad_metalad/tests/test_add.py
- datalad_metalad/tests/test_extract.py
This PR addresses issue #79 and obsoletes issue #78
`meta-extract` will not store metadata any longer, but report it to the output channels as JSON-string.
`meta-add` can be used to save the metadata  in a metadata model instance, and consequently in a metadata store
> Remove metadata storage from meta extract

- datalad_metalad/extract.py
- datalad_metalad/tests/test_extract.py
- tools/extract_core_metadata.py
This PR streamlines the behavior of meta-extract w.r.t. the approach that either a file or a dataset is extracted in a single invocation of meta-extract.
Meta-extract will not try to extract directories any longer. That means it will also not extract a sub-dataset as part of a file-level extraction. (There is a loss of information that we have to discuss, i.e. the hasPart-, and isPartOf-elements of the JSON-LD description. This could be added by filters for example).
To extract sub-datasets, perform a dataset-level extraction on them and either add them to a super-dataset metadata store with the appropriate additional keys (inter_dataset_path, root_dataset_id, root_dataset_version) or aggregate the metadata into the super dataset.
This PR also fixes the description: extraction parameters …
> Meta extract consolidation

- datalad_metalad/dump.py
- datalad_metalad/exceptions.py
This fixes issue #78 and parts of issue #103
Meta-dump will report on invalid metadata and, by using the updated metadata model, report old metadata versions, that cannot be processed any longer
> Improve meta-dump error reporting

- datalad_metalad/add.py
- datalad_metalad/aggregate.py
- datalad_metalad/dump.py
- datalad_metalad/extract.py
- datalad_metalad/tests/test_add.py
- datalad_metalad/tests/test_aggregate.py
- datalad_metalad/tests/utils.py
- datalad_metalad/utils.py
- tools/extract_metadata.py
This PR fixes #119 , #115 , and #97 
Metadata-store is no longer used in the API (cmdline and coreapi). Instead we assume that metadata over elements of a dataset is stored in the git-repo of that dataset
> Use datasets instead of metadata stores in UI

- datalad_metalad/add.py
- datalad_metalad/aggregate.py
- datalad_metalad/dump.py
- datalad_metalad/extract.py
- datalad_metalad/tests/test_add.py
- datalad_metalad/tests/test_aggregate.py
This fixes issue #84 and issue #85 
The dump result record now contains the result that is emitted by the custom renderer as verbatim value in the key "metadata".
> Fix result structure

- datalad_metalad/extract.py
- datalad_metalad/tests/test_extract.py
meta-extract now interprets a context dictionary. The dictionary can be either given as JSON-string or dictionary (in an API call).
meta-extract reads the dataset version from the dictionary, if present, via the key "dataset_version".
If the version is given in the context, meta-extract does not have to call dataset.repo.get_hexsha(), which can be quite expensive.
> Add context parameter to meta-extract

- datalad_metalad/__init__.py
- datalad_metalad/add.py
- datalad_metalad/conduct.py
- datalad_metalad/dump.py
- datalad_metalad/extract.py
- datalad_metalad/filters/base.py
- datalad_metalad/pathutils/tests/test_treesearch.py
- datalad_metalad/pipelineelement.py
- datalad_metalad/pipelines/extract_metadata_pipeline.json
- datalad_metalad/pipelines/extract_metadata_pipeline_auto.json
- datalad_metalad/processor/add.py
- datalad_metalad/processor/autodrop.py
- datalad_metalad/processor/autoget.py
- datalad_metalad/processor/base.py
- datalad_metalad/processor/extract.py
- datalad_metalad/provider/base.py
- datalad_metalad/provider/datasettraverse.py
- datalad_metalad/tests/test_conduct.py
- datalad_metalad/utils.py
- requirements-devel.txt
Introduce the first implementation of the new command meta-conduct to enable pipeline processing. Pipelines are given as JSON objects (in the future also YAML), that describe which metalad commands, aka _pipeline_ _elements_, should be run in which order.
Currently pipeline elements consists of a thin wrapper around metalad commands, for example `meta-add` and `meta-extract`. Those elements fetch the results that upstream pipeline yielded and route them to the _correct_ arguments of the underlying metalad command. For example: an upstream element might generate a result containing a dataset path. The pipeline element that wraps meta-add will pick up the result and route it to the `-d`/`dataset` argument  of `meta_add`.
From the previous explanation, it should be clear, that a part of the …
> Pipeline implementation v 0.1

- .appveyor.yml
- datalad_metalad/extract.py
- datalad_metalad/extractors/tests/test_annex.py
- datalad_metalad/extractors/tests/test_base.py
- datalad_metalad/extractors/tests/test_custom.py
- datalad_metalad/extractors/tests/test_runprov.py
- setup.py
Fix tests to work with:
With the next release that should fix metalad extension CI-board in datalad/extensions
> fix extractor tests

- datalad_metalad/conduct.py
- datalad_metalad/pipelineelement.py
- datalad_metalad/processor/add.py
- datalad_metalad/processor/extract.py
- datalad_metalad/tests/test_conduct.py
This PR fixes an issue where meta-conduct puts an object into the datalad result dict. This is an error, instead a JSON-object should be put there.
> meta-conduct: return JSON-encoded results

- datalad_metalad/processor/add.py
- datalad_metalad/processor/extract.py
- datalad_metalad/provider/datasettraverse.py
Labels such as "file", "dataset", and "both" are now compared case-insensitive.
> Use case insensitive comparison of labels in `meta-conduct`

- datalad_metalad/add.py
- datalad_metalad/tests/test_add.py
- datalad_metalad/utils.py
This PR enables `meta-add` to add multiple records in a single invocation or call.
Adding multiple records in a single call greatly reduces the overhead that stems from locking/unlocking the backend, writing out dataset tree version lists and uuid sets, writing out references. The number of records that can be added at once is only limited by the memory available (and, of course, the disk space).
The metadata argument is now considered to contain either a string, that identifies a JSON-file, a single metadata record, i.e. a  dictionary, or a list of metadata records If a file is given, it must also contain either a single dictionary or a list of dictionaries, where each dictionary describes a metadata record.
> Enable `meta-add` to add multiple records in a single call

- datalad_metalad/add.py
- datalad_metalad/aggregate.py
- datalad_metalad/tests/test_add.py
- datalad_metalad/tests/test_locking.py
- requirements.txt
This PR uses the `lock_backend()` context manager to lock the backend. This ensures the release of locks in case of an exception.
> Use `locked_backend()` context manager to lock the backend

- datalad_metalad/add.py
- datalad_metalad/tests/test_add.py
This PR fixes issue #208 
It implements a cache that is used in _batch-mode_ to collect metadata records. Those records are written whenever the cache hits a certain size or a certain age.
In _batch-mode_ `meta-add` will now acknowledge caching for each entered metadata record. When `stdin` is closed, `meta-add` will return a count of successfully written records and records that could not be written. Which records were written is not reported.
> Cache metadata records in `meta-add` to reduce write-lock holding time

- datalad_metalad/extractors/tests/test_studyminimeta.py
This commit adds a regression test for the availability of the studyminimeta-module. The module might not be present due to a faulty specification in `setup.py` or `setup.cfg`.
This should prevent re-appearence of issue #247
> Add a test for studyminimeta module availability

- datalad_metalad/pipeline/provider/datasettraverse.py
- datalad_metalad/pipeline/provider/tests/test_datasettraverse.py
Fixes #253 
This PR fixes issue #253, i.e. the faulty handling of a relative path in DatasetTraverser's top-level-dir arguments.
> Fix relative path resolution in DatasetTraverser

- datalad_metalad/extractors/core.py
- requirements.txt
Fixes #255 
This PR disables the result renderer when calling `Dataset.subdatasets()`. As a result the extractor execution will no longer yield subdataset names.
> Disable result renderer in subdataset in core extractor calls

- datalad_metalad/pipeline/provider/datasettraverse.py
- datalad_metalad/pipeline/provider/tests/test_datasettraverse.py
Fixes #256 
This PR fixes insufficient path canonization in the DatasetTraverser constructor.
Unresolved path arguments, e.g. '/home/dataset0/../dataset0/subdataset1', are
now resolved, i.e. converted to '/home/dataset0/subdataset1'. This prevents an
error that is otherwise raised in a `Path.relative_to()`
> Fix traverser-error on unresolved top_level_dir path argument

- datalad_metalad/extractors/tests/test_base.py
This commit improves the interpretation of the `__version__` string from `datalad._version` in order to handle local version labels properly, i.e. ignore them, when determining major, minor, and patch numbers.
This fixes failing metalad-extension tests on datalad PRs.
- fix failing metadata-extension tests on datalad PRs
> fix the determination of the datalad version

- datalad_metalad/conduct.py
- datalad_metalad/extract.py
- datalad_metalad/tests/test_extract.py
- requirements-devel.txt
- setup.cfg
- tools/extract_metadata.py
In order to provide extractor parameter to a dataset-level extraction call, metalad has to detect, that the arguments following the extractor are not a file path and potentially further extractor parameter, but extractor parameter for a dataset-level extractor. To do that, the caller has to provide a **delimiter**. This was previously `--`. But `argparse`, which is used by `datalad` swallows a `--`-argument.
Therefore the flag `--force-dataset-level` is added to indicate that the arguments following the extractor name are only extractor arguments and not a path, and that a dataset-level extraction is requested.
This PR basically replaces PR #262
> Replace positional `--`-argument with `--force-dataset-level`-flag 

- datalad_metalad/extract.py
- datalad_metalad/tests/test_extract.py
This PR fixes issue #266
It adds absolute path handling for metadata paths. It also catches the state where the provided file is not tracked by git or git-annex and raises a `ValueError`.
> Support absolute intra-dataset paths and catch not-tracked errors

- .appveyor.yml
- datalad_metalad/extractors/tests/test_annex.py
- datalad_metalad/extractors/tests/test_base.py
- datalad_metalad/extractors/tests/test_custom.py
- datalad_metalad/extractors/tests/test_runprov.py
- datalad_metalad/metadatatypes/tests/test_metadata.py
- datalad_metalad/pipeline/provider/tests/test_datasettraverse.py
- datalad_metalad/tests/__init__.py
- datalad_metalad/tests/test_add.py
- datalad_metalad/tests/test_extract.py
- datalad_metalad/tests/test_locking.py
- datalad_metalad/tests/utils.py
This PR fixes potential tests errors by replacing `os.chdir()` with the `datalad.tests.utils.chpwd()` context handler.
In addition it disables the result renderer for test-internal datalad-api calls.
> Improve tests, fix potential errors and reduce log output

- datalad_metalad/tests/test_extract.py
This PR uses a mock attribute for testing that works in different python version >= 3.7
> Use proper mock attributes for testing

- .appveyor.yml
- .github/workflows/docbuild.yml
- datalad_metalad/extract.py
- datalad_metalad/extractors/custom.py
- datalad_metalad/extractors/tests/test_annex.py
- datalad_metalad/extractors/tests/test_base.py
- datalad_metalad/extractors/tests/test_custom.py
- datalad_metalad/extractors/tests/test_runprov.py
- datalad_metalad/extractors/tests/test_studyminimeta.py
- datalad_metalad/indexers/tests/test_jsonld.py
- datalad_metalad/indexers/tests/test_studyminimeta.py
- datalad_metalad/pipeline/provider/tests/test_datasettraverse.py
- datalad_metalad/pipeline/provider/tests/test_metadatatraverser.py
- datalad_metalad/tests/__init__.py
- datalad_metalad/tests/test_add.py
- datalad_metalad/tests/test_aggregate.py
- datalad_metalad/tests/test_conduct.py
- datalad_metalad/tests/test_extract.py
- datalad_metalad/tests/test_filter.py
- datalad_metalad/tests/test_locking.py
- datalad_metalad/tests/utils.py
- requirements-devel.txt
- requirements.txt
- setup.cfg
- tox.ini
This PR fixes issue [datalad-catalog #172] (https://github.com/datalad/datalad-catalog/issues/172)
The problem was intermixing of functions that preserve symlinks, i.e. `Dataset`-functions and functions that resolve symlinks, i.e. `GitRepo`-functions.
> Fix symlink issue

- CHANGELOG.md
- datalad_metalad/extract.py
This PR changes two path-related calculations
1. The calculation of a relative file-path from
an absolute file-path now takes in account,
that the path might contain a symlink
2. The determination of the file-status now
bases the file path on the resolved dataset
path, if the dataset path contains a symlink
> Fix file-path determination if dataset-path or file-path contain symlinks

- datalad_metalad/extract.py
- datalad_metalad/tests/test_extract.py
This PR fixes issue #277, where a call to `subatasets()` during `meta-extract` did not contain the keyword-arguments `result_renderer=disabled` and the status output from the `subdatasets()`-call scrambled the JSON output result.
> Fix JSON output of `meta-extract`, which is scrambled by status-messages from `subdatasets()`-calls

- .appveyor.yml
- datalad_metalad/aggregate.py
This PR sets the number of required path arguments in `meta-aggregate` to "one or more". This leads to proper usage- and help-messages and fixes #275.
In addition, this PR adds constraints on the branches that are tested by default in appveyor. Now only `master` and `maint_0.4` are tested if pushed to. This prevents duplicate test runs for issue-branches with a PR. Note: you have to have a PR to test an issue branch in appveyor now.
> Fix number of required path arguments in meta-aggregate interface

- datalad_metalad/aggregate.py
- datalad_metalad/utils.py
- requirements-devel.txt
- requirements.txt
- setup.cfg
This PR improves the description of the arguments that have to be provided to `meta-aggregate`. It also adds a check to detect the error condition that an aggregation of metadata onto itself is requested.
This PR also updates the minimal required version of `datalad-metadata-model` to `0.3.5`. This fixes problems with spaces in file names
> Improve `meta-aggregate` argument handling

- datalad_metalad/extractors/tests/test_custom.py
This PR removes the dependency of `datalad.simplejson`, by replacing it with `json`.
Fixes #285
> Replace `simplejson` with `json`

- datalad_metalad/__init__.py
- datalad_metalad/extract.py
- datalad_metalad/extractors/legacy/tests/test_audio.py
- setup.cfg
Fixes #288 
This PR fixes two errors:
1. Fix python and datalad dependency definitions to ensure that test data is contained within the distribution package
2. Ensure selection of `datalad_metalad` contained extractors over extractors with the same name from `datalad`
> Fix dependencies

- tox.ini
This PR follows the metalad extension failure in https://github.com/datalad/datalad/pull/7170
> TST: Don't error out on deprecation warnings

- datalad_metalad/dump.py
Fixes #305 
Intermediate dataset nodes might have a None-MRR if they do have neither file nor dataset metadata. This PR checks for None-MRRs and skips dumping them.
> Do not try to dump a None-MRR

- .appveyor.yml
This PR uses macos-moneterey image to run MacOS tests on appveyor
> Move MacOS test to monterey

- datalad_metalad/dump.py
Should fix #305 
This PR ensures that metalad checks whether there is actually a metadata root record (MRR) at a certain dataset path-level before trying to dump metadata.
It is wrong to assume that there is always an MRR, because the dataset tree can contain nodes that do not represent a dataset and have therefore no MRR.
> Check for None Metadata Root Record in search

- docs/source/index.rst
- docs/source/user_guide/index.rst
- docs/source/user_guide/writing-extractors.rst
This PR introduces a "User guide" section to the docs, and adds a draft of a user guide on writing custom extractors, addressing #281 
This is a rather rough draft, based on what I was able to piece together from reading or experimentation, with some statements being just my educated guesses. I also left a couple of TODOs in the text. Since I'll be away for a while, please feel free to hack away on the descriptions. I've allowed edits by maintainers, so you should be able to push changes.
As a side note, I formatted the text with 1 sentence per line (with exceptions) - for me it works well, because then whole sentences can be commented/edited.
> Add a draft of a user guide on writing custom extractors

- _datalad_buildsupport/__init__.py
- _datalad_buildsupport/formatters.py
- _datalad_buildsupport/setup.py
- docs/source/acknowledgements.rst
- docs/source/api.rst
- docs/source/conf.py
- docs/source/extractors.rst
- docs/source/index.rst
This PR fixes a few issues I had filed two weeks ago:
- it restructures the index toc tree to make the navbar less cluttered (fixes #312)
- It adds the ``meta-add`` command (fixes #311)
- It adds the ``meta-conduct`` command (fixes #313)
- If gives the docs the proper name (fixes #310)
- It adds the current year to the copyright and keeps it up to date
- It moves the user guide section upwards (fairly subjective change)
Individual commit messages contain additional info and references to issues. Feel free to drop any commit you disagree with.
Here is how the index page looks with these changes:
versus how it currently looks:
> DOC: A variety of small improvements to the docs

- datalad_metalad/add.py
- datalad_metalad/tests/test_add.py
- setup.cfg
Fixes #322 
This commit fixes a bug in which sub-dataset entries in the tree-version-list and in the uuid-set would be overriden, if the dataset was a sub-dataset.
The changed code correctly re-uses the top-level nodes that already contain the sub-dataset when adding the super-dataset instead of creating new, empty top-level nodes.
> include root-dataset and sub-dataset in UUID-set

- .codespellrc
- .github/workflows/codespell.yml
- Makefile
- _datalad_buildsupport/formatters.py
- datalad_metalad/__init__.py
- datalad_metalad/aggregate.py
- datalad_metalad/extractors/core.py
- datalad_metalad/extractors/tests/test_base.py
- datalad_metalad/filters/base.py
- docs/source/user_guide/writing-extractors.rst
- tox.ini
In the excitement of coming up hackathon and also since https://github.com/datalad/datalad-extension-template/pull/45 has been debated for nearly half a year, decided to make at least this one a little more a better spelled one ;)
> Codespell: adding config, workflow and fixing some typos

- datalad_metalad/extract.py
- datalad_metalad/extractors/base.py
- datalad_metalad/tests/test_extract.py
- docs/source/user_guide/writing-extractors.rst
This PR:
- Adds logic to `extract.py` to allow either a returned `bool` or a yielded`Generator` to be interpreted correctly: If an extractor implements logic where any result record is yielded with a failure 'status' (i.e. equal to 'impossible' or 'error') the extractor infrastructure will signal an error and the extractor's extract method will not be called.
- Updates the docstring of `DatasetMetadataExtractor.get_required_content()` in `extractors/base.by` to indicate this change, especially to developers implementing extractors 
- Adds missing `return` statements in `extract.py` where failures are yielded
- Updates related documentation
- Closes https://github.com/datalad/datalad-metalad/issues/356
> ENH: Allow `DatasetMetadataExtractor.get_required_content()` to return a generator

- datalad_metalad/extract.py
- datalad_metalad/extractors/base.py
- datalad_metalad/tests/test_extract.py
This PR:
- moves the `get_required_content` method to the base class `MetadataExtractorBase` so that both `FileMetadataExtractor` and `DatasetMetadataExtractor` can make use of it (addresses https://github.com/datalad/datalad-metalad/issues/287)
- refactors `extract.py` in order to deduplicate code, and updates related tests (addresses https://github.com/datalad/datalad-metalad/issues/366):
- merges `do_file_extraction()` and `do_dataset_extraction()` into a single function `do_extraction()`, with a new argument `extractor_type`, which would be either `'file'` or `'dataset'`.
- merges `perform_file_metadata_extraction()` and `perform_dataset_metadata_extraction()` into a single function `perform_metadata_extraction()`
> MNT: Refactor extraction code

- datalad_metalad/__init__.py
- datalad_metalad/extractors/base.py
This way we could quickly tell one "generation" of things from another. To be used in https://github.com/datalad/datalad-metalad/issues/340 .
I don't mind if later or now it is formalized even better. FWIW in now deprecated `search` we have
```python
metadata_source=Parameter(
args=('--metadata-source',),
choices=('legacy', 'gen4', 'all'),
doc="""if given, defines which metadata source will be used to
search. 'legacy' will limit search to metadata in the old format,
i.e. stored in '$DATASET/.datalad/metadata'. 'gen4' will limit
search to metadata stored by the git-backend of 
'datalad-metadata-model'. If 'all' is given, metadata from all
supported sources will be included in the search. The default is
'legacy'.""")
```
so I used "compatible" identifiers here.
> Add __generation__ to metadata extractors to be able to tell one from another

- datalad_metalad/extract.py
This was supposed to be part of https://github.com/datalad/datalad-metalad/pull/367, but fell through the cracks. This addition ensures that the correct type is displayed in the metadata record output from `meta-extract`
> BUG: fix extractor type in `metadata_record`

- datalad_metalad/add.py
- datalad_metalad/aggregate.py
- datalad_metalad/conduct.py
- datalad_metalad/dump.py
- datalad_metalad/extract.py
- datalad_metalad/extractors/annex.py
- datalad_metalad/extractors/base.py
- datalad_metalad/extractors/core.py
- datalad_metalad/extractors/custom.py
- datalad_metalad/extractors/external_dataset.py
- datalad_metalad/extractors/external_file.py
- datalad_metalad/extractors/metalad_example_dataset.py
- datalad_metalad/extractors/metalad_example_file.py
- datalad_metalad/extractors/runprov.py
- datalad_metalad/extractors/studyminimeta/main.py
- datalad_metalad/extractors/tests/test_annex.py
- datalad_metalad/extractors/tests/test_base.py
- datalad_metalad/extractors/tests/test_custom.py
- datalad_metalad/extractors/tests/test_runprov.py
- datalad_metalad/filter.py
- datalad_metalad/filters/base.py
- datalad_metalad/tests/test_add.py
- datalad_metalad/tests/test_aggregate.py
- datalad_metalad/tests/test_conduct.py
- datalad_metalad/tests/test_extract.py
- datalad_metalad/tests/test_filter.py
Just fixing a minor annoyance :)
AFAIK you'd always want expandtab for python.
> Expand tabs

- datalad_metalad/extract.py
- setup.cfg
Fixes https://github.com/datalad/datalad-metalad/issues/376
> BF: imports `BaseMetadataExtractor` from `datalad-deprecated`

- datalad_metalad/add.py
I'm trying to give meta-add result records (when not running in batch mode). Would this be the way to go? (CC @mih, @yarikoptic)
> Render result reports for meta-add if not run in batch-mode

- datalad_metalad/extract.py
- datalad_metalad/tests/test_extract.py
This fixes #354. 
However, its only one step towards a proper solution. As outlined by @mih in the chat, the ``path`` argument of ``meta-extract`` should ideally get a constraint such as ``EnsurePath(lexists=True)`` (https://github.com/datalad/datalad-next/blob/c3f60e9e55ab0d9e77fb5cc2f02479a092445cc8/datalad_next/constraints/basic.py#L328) that can perform this input validation automatically before the command runs. This change is more along the lines of how-we-do-it-in-core (add a series of sanity checks at the start of a command)
Nevertheless, its an improvement from the status quo (which delayed raising the error to the last possible point in time, after an internal status call didn't return a status, and raised it with less informative error about the lack of a dataset status), and …
> BF: Raise early and informative when extracting from a non-existing file

- datalad_metalad/extract.py
- datalad_metalad/extractors/tests/test_base.py
- datalad_metalad/filter.py
- datalad_metalad/utils.py
- requirements-devel.txt
This PR replaces the deprecated and removed `pkg_resources` with `importlib.metadata`. This PR fixes issue #397
> Replace `pkg_rsources` with `importlib.metadata`

- datalad_metalad/extractors/tests/test_base.py
- datalad_metalad/filter.py
- datalad_metalad/utils.py
- requirements-devel.txt
- requirements.txt
This PR should fix an error related to changes in the import interface between python 3.8 and python 3.9
> Fix importlib error

- datalad_metalad/extractors/tests/test_base.py
- datalad_metalad/filter.py
- requirements-devel.txt
- requirements.txt
This PR specifies minimum versions for `importlib-metadata` and `importlib-resources`.
> Specify minimum version of `importlib-metadata` and `importlib-resources`

- datalad_metalad/extract.py
- datalad_metalad/extractors/base.py
Fixes #407 
This PR removes the definition of the legacy extractor base class `BaseMetadataExtractor` from `datalad_metalad.extractors.base`. It now is imported from `datalad_deprecated.metadata.extractors.base` and augmented with a generation-ID.
> Remove redefinition of legacy extractor base-class
