datalad/datalad-metalad

- datalad_metalad/__init__.py
- datalad_metalad/extractors/core.py
Actually part of a bigger PR, but just to see if the configuration of all pieces works for this repo.
> RF+BF: ID generation helpers, don't fail on simple contexts

- README.md
- datalad_metalad/__init__.py
- datalad_metalad/aggregate.py
- datalad_metalad/dump.py
- datalad_metalad/extractors/tests/test_annex.py
- datalad_metalad/extractors/tests/test_base.py
- datalad_metalad/extractors/tests/test_custom.py
- datalad_metalad/extractors/tests/test_runprov.py
- datalad_metalad/tests/__init__.py
- datalad_metalad/tests/test_aggregate.py
- datalad_metalad/tests/test_base.py
- datalad_metalad/tests/test_extract.py
- datalad_metalad/tests/test_report.py
- docs/source/index.rst
- setup.py
> Departure from revolution

- datalad_metalad/aggregate.py
- datalad_metalad/tests/test_aggregate.py
- datalad_metalad/utils.py
Document syntax, make work consistently, test.
Also fixes the inconsistent behavior reported in gh-12
> RF+BF+TST+DOC: Aggregation of aggregates

- datalad_metalad/dump.py
- datalad_metalad/utils.py
(There weren't much, I hope I didn't miss any)
> RF: rev_resolve_path -> resolve_path, fixes #31

- setup.py
To pull in fixes for git-annex behavior change (dotfile inclusion).
> BF: Further tighten dependency on DataLad

- datalad_metalad/extractors/core.py
- datalad_metalad/extractors/runprov.py
Anticipated eventual removal via https://github.com/datalad/datalad/pull/4698
> Use GitRepo.call_git*() instead of private _git_custom_command()

- datalad_metalad/extract.py
> Improve meta-extract error report

- datalad_metalad/aggregate.py
- datalad_metalad/utils.py
This fixes issue #88 
Meta-aggregate will now report, if nothing has to be done.
> Improve state and error reporting in meta-aggregate

- datalad_metalad/aggregate.py
- datalad_metalad/tests/test_aggregate.py
This PR fixes #111 
Tests for meta-aggregate with basic coverage
> Tests for meta-aggregate

- datalad_metalad/add.py
- datalad_metalad/aggregate.py
- datalad_metalad/utils.py
- requirements-devel.txt
> Move locks to .datalad/locks

- datalad_metalad/extract.py
- datalad_metalad/tests/test_extract.py
Add --get-context parameter to meta-extract. It instructs meta-extract to return a context and exit.
> Add --get-context parameter to meta-extract

- datalad_metalad/dump.py
This PR modifies dump in such a way that it will report metadata for all versions of datasets. That might lead to "duplicate" results if the same metadata was extracted in multiple dataset versions
> Display metadata for all dataset versions in dump

- datalad_metalad/dump.py
- datalad_metalad/tests/test_conduct.py
Identify remote repository location and ensure correct metadata reporting from remote location
> NF Remote dump

- datalad_metalad/add.py
- datalad_metalad/consumer/base.py
- datalad_metalad/tests/test_add.py
- datalad_metalad/tests/utils.py
This PR implements a batch mode for meta-add.
> Add batch mode to meta-add

- datalad_metalad/add.py
Fixes issue #196 and issue [datalad/datalad #6340](https://github.com/datalad/datalad/issues/6340)
> add missing stdout.flush() calls to meta-add

- README.md
- datalad_metalad/__init__.py
- datalad_metalad/add.py
- datalad_metalad/aggregate.py
- datalad_metalad/extract.py
- datalad_metalad/extractors/annex.py
- datalad_metalad/extractors/base.py
- datalad_metalad/extractors/core.py
- datalad_metalad/extractors/core_dataset.py
- datalad_metalad/extractors/core_file.py
- datalad_metalad/extractors/custom.py
- datalad_metalad/extractors/external_file.py
- datalad_metalad/extractors/runprov.py
- datalad_metalad/extractors/studyminimeta/main.py
- datalad_metalad/filter.py
- datalad_metalad/filters/base.py
- datalad_metalad/filters/demofilter.py
- datalad_metalad/metadatatypes/metadata.py
- datalad_metalad/metadatatypes/tests/test_metadata.py
- datalad_metalad/pipeline/consumer/add.py
- datalad_metalad/pipeline/consumer/tests/test_add.py
- datalad_metalad/pipeline/provider/metadatatraverse.py
- docs/source/design/datatypes.rst
- docs/source/index.rst
Enable consumer.add to aggregate metadata, if desired
> Add aggregate capability to consumer.add

- requirements.txt
> Use datalad-metadata-model version 0.2.0rc3

- datalad_metalad/__init__.py
- datalad_metalad/extract.py
- datalad_metalad/extractors/external.py
- datalad_metalad/tests/test_extract.py
> Fix Issue 243: `get_required_content()` not called

- CHANGELOG.md
This PR updates the changelog for the 0.4.1 release
> Prepare changelog for 0.4.1 release

- datalad_metalad/add.py
- datalad_metalad/aggregate.py
- datalad_metalad/conduct.py
- datalad_metalad/dump.py
- datalad_metalad/extract.py
- datalad_metalad/filter.py
- requirements-devel.txt
- requirements.txt
- setup.cfg
> Adapt metalad to datalad 0.18

- .appveyor.yml
> Switch macOS appveyor builds to Monterey

- requirements-devel.txt
- requirements.txt
> Clean up historical comment that was addressed

- datalad_metalad/extractors/tests/test_runprov.py
- requirements-devel.txt
This PR adds the `pre-commit` package to the list of development requirements in `requirements-devel.txt`
> Add pre-commit package to the development requirements

- datalad_metalad/extractors/annex.py
- datalad_metalad/extractors/core.py
- datalad_metalad/extractors/custom.py
- datalad_metalad/extractors/runprov.py
- datalad_metalad/extractors/tests/test_annex.py
- datalad_metalad/extractors/tests/test_custom.py
- datalad_metalad/extractors/tests/test_runprov.py
- datalad_metalad/tests/__init__.py
- requirements-devel.txt
- requirements.txt
- setup.cfg
> Remove package `six` and its usage
